runtime: go
api_version: go1.8

handlers:
- url: /.*
  script: _go_app
  secure: always

env_variables:
  # Your settings
  LINE_CHANNEL_SECRET: 
  LINE_CHANNEL_TOKEN: 
  LINE_GROUP_ID: 
  FIREBASE_BASE_URL: 
  FIREBASE_SECRET: 